let arr=[];
arr.push(1);
console.log(arr);
arr.push(2,3);
console.log(arr);
arr.pop();
console.log(arr);
let a=arr.pop();
console.log(arr);
arr.unshift(29);
console.log(arr);
arr.unshift(9,20);
console.log(arr);
arr.shift();
console.log(arr);
let b=arr.shift();
console.log(b);
arr.splice(1);
console.log(arr);
arr.splice(1,5,6,7,8,95);
console.log(arr);
arr.splice(1,1,30);
console.log(arr);
arr.push(30,40,50);
console.log(arr);
arr.pop();
console.log(arr);
arr.unshift(10);
console.log(arr);
arr.shift();
console.log(arr);
